version: '3.7'
services:
  micro-proyecto:
    container_name: micro-proyecto
    image : micro-proyecto:v1
    build:
      context: .
    ports:
      - "4001:4001"
    networks:
      - micro-proyecto-app
networks: 
  micro-proyecto-app: